import './js/modal';
import './js/button_wave';
import './js/button__more';
import './js/slider';
import '../node_modules/slick-carousel/slick/slick';
import './js/popap';
import '../node_modules/jquery/src/jquery';
import '../node_modules/jquery/src/ajax';
import '../node_modules/jquery/dist/jquery';
